version: "3"
services: 
   mongo: 
      image: mongo:3.6-jessie
      restart: always
      ports: 
        - "27017:27017"
      volumes: 
        - web_db_1:/data/db
   mongo-express: 
      image: mongo-express:latest
      links: 
        - mongo:mongo
      ports: 
        - "18081:8081"
   node-express: 
      build:
         context: .
         dockerfile: ./build/express/Dockerfile
      command: npm run dev
      volumes: 
        - ./mm-thx-counter:/home/app/mm-thx-counter 
        - /home/app/mm-thx-counter/node_modules
      links: 
        - mongo:mongodb
      ports:
        - "13000:3000"
   nginx:
      image: nginx:alpine
      ports:
        - "18080:18080"
      volumes:
        - "./conf.d:/etc/nginx/conf.d"
      links:
        - node-express:node-express
        - mongo-express:mongo-express
volumes: 
   web_db_1: 
      driver: local
  
